import { useState, useMemo } from "react";
import { Search } from "lucide-react";

// Bilingual keyword map for emoji search (PT & EN)
const EMOJI_KEYWORDS: Record<string, string> = {
  "😀": "sorriso grinning smile feliz happy alegre",
  "😃": "sorriso grande big smile feliz happy",
  "😄": "sorriso olhos smiling eyes feliz happy",
  "😁": "sorriso radiante beaming feliz",
  "😆": "sorriso apertado squinting rindo laughing",
  "😅": "sorriso suor sweat nervoso nervous",
  "🤣": "rolando rindo floor laughing chorando crying",
  "😂": "chorando rindo tears joy lágrimas alegria",
  "🙂": "leve sorriso slightly smiling",
  "🙃": "cabeça baixo upside down invertido",
  "😉": "piscando winking piscar wink",
  "😊": "sorriso tímido smiling shy",
  "😇": "anjo halo angel auréola",
  "🥰": "amor corações hearts love apaixonado",
  "😍": "olhos coração heart eyes amor love",
  "🤩": "estrelas stars empolgado excited",
  "😘": "beijo blow kiss beijinho",
  "😗": "beijando kissing beijo",
  "😚": "beijo olhos fechados kissing closed eyes",
  "😙": "beijo sorrindo kissing smiling",
  "🥲": "sorriso lágrima tear smile triste sad",
  "😋": "delícia saboreando savoring food yummy",
  "😛": "língua tongue mostrando",
  "😜": "piscando língua winking tongue",
  "🤪": "maluco zany louco crazy",
  "😝": "língua apertado squinting tongue",
  "🤑": "dinheiro money boca cifrão",
  "🤗": "abraço hug abraçando hugging",
  "🤭": "mão boca hand mouth risada giggle",
  "🤫": "silêncio shush quiet calado",
  "🤔": "pensando thinking pensativo hmm",
  "🤐": "zíper boca zipper mouth calado",
  "🤨": "sobrancelha eyebrow suspeito suspicious",
  "😐": "neutro neutral sério",
  "😑": "sem expressão expressionless",
  "😶": "sem boca no mouth silêncio",
  "😏": "malicioso smirk convencido",
  "😒": "entediado unamused chateado",
  "🙄": "revirando olhos rolling eyes",
  "😬": "careta grimace desconfortável awkward",
  "😌": "aliviado relieved tranquilo calm",
  "😔": "pensativo pensive triste sad",
  "😪": "sonolento sleepy sono",
  "🤤": "babando drooling baba",
  "😴": "dormindo sleeping sono zzz",
  "😷": "máscara mask doente sick",
  "🤒": "termômetro thermometer doente febre fever",
  "🤕": "bandagem bandage machucado hurt",
  "🤢": "nauseado nauseated enjoo nausea",
  "🤮": "vomitando vomiting enjoo",
  "🥵": "quente hot calor heat",
  "🥶": "frio cold gelado freezing",
  "🥴": "tonto woozy zonzo dizzy",
  "😵": "tonto olhos x crossed out dizzy",
  "🤯": "cabeça explodindo exploding mind blown",
  "🤠": "cowboy chapéu vaqueiro",
  "🥳": "festa party comemoração celebration",
  "😎": "óculos sol sunglasses cool legal",
  "🤓": "nerd óculos glasses estudioso",
  "🧐": "monóculo monocle investigando",
  "😕": "confuso confused",
  "😟": "preocupado worried",
  "🙁": "triste frowning sad",
  "😮": "boca aberta open mouth surpreso surprised",
  "😯": "hushed surpreso surprised",
  "😲": "assustado astonished espantado",
  "😳": "corado flushed envergonhado embarrassed",
  "🥺": "pidão pleading por favor please",
  "😦": "triste boca aberta frowning",
  "😧": "angustiado anguished",
  "😨": "medo fearful assustado scared",
  "😰": "ansioso anxious sweat suor",
  "😥": "triste aliviado sad relieved",
  "😢": "chorando crying lágrima tear triste",
  "😭": "chorando muito loudly crying triste sad",
  "😱": "gritando screaming medo fear terror",
  "😖": "confuso confounded",
  "😣": "perseverando persevering",
  "😞": "desapontado disappointed triste",
  "😓": "suor downcast",
  "😩": "cansado weary exausto",
  "😫": "cansado tired exausto",
  "🥱": "bocejando yawning sono sleepy",
  "😤": "raiva steam nose bravo angry",
  "😡": "raiva enraged bravo furioso angry",
  "😠": "bravo angry raiva",
  "🤬": "palavrão swearing bravo angry",
  "😈": "diabo devil sorrindo smiling chifres horns",
  "👿": "diabo bravo angry devil",
  "💀": "caveira skull morte death",
  "💩": "cocô poo merda poop",
  "🤡": "palhaço clown",
  "👹": "ogro ogre monstro monster",
  "👺": "duende goblin",
  "👻": "fantasma ghost",
  "👽": "alien alienígena extraterrestre",
  "👾": "monstro alien monster space invader",
  "🤖": "robô robot",
  "😺": "gato sorrindo grinning cat",
  "😸": "gato sorriso cat smiling",
  "😹": "gato chorando rindo cat tears joy",
  "😻": "gato coração cat heart eyes amor",
  "😼": "gato malicioso cat wry smile",
  "😽": "gato beijo kissing cat",
  "🙀": "gato assustado weary cat",
  "😿": "gato chorando crying cat triste",
  "😾": "gato bravo pouting cat",
  "🐶": "cachorro dog cara face",
  "🐱": "gato cat cara face",
  "🐭": "rato mouse cara face",
  "🐹": "hamster",
  "🐰": "coelho rabbit bunny",
  "🦊": "raposa fox",
  "🐻": "urso bear",
  "🐼": "panda",
  "🐨": "coala koala",
  "🐯": "tigre tiger cara face",
  "🦁": "leão lion",
  "🐮": "vaca cow cara face",
  "🐷": "porco pig cara face",
  "🐸": "sapo frog",
  "🐵": "macaco monkey cara face",
  "🙈": "macaco olhos see no evil monkey",
  "🙉": "macaco ouvidos hear no evil monkey",
  "🙊": "macaco boca speak no evil monkey",
  "🐔": "galinha chicken frango",
  "🐧": "pinguim penguin",
  "🐦": "pássaro bird",
  "🦆": "pato duck",
  "🦅": "águia eagle",
  "🦉": "coruja owl",
  "🦇": "morcego bat",
  "🐺": "lobo wolf",
  "🐴": "cavalo horse cara face",
  "🦄": "unicórnio unicorn",
  "🐝": "abelha bee honeybee",
  "🦋": "borboleta butterfly",
  "🐌": "caracol snail",
  "🐞": "joaninha ladybug lady beetle",
  "🐜": "formiga ant",
  "🐢": "tartaruga turtle",
  "🐍": "cobra snake serpente",
  "🦎": "lagarto lizard",
  "🐙": "polvo octopus",
  "🐬": "golfinho dolphin",
  "🐳": "baleia whale",
  "🐋": "baleia whale",
  "🦈": "tubarão shark",
  "🐊": "crocodilo crocodile jacaré",
  "🐅": "tigre tiger",
  "🐆": "leopardo leopard onça",
  "🦍": "gorila gorilla",
  "🐘": "elefante elephant",
  "🐪": "camelo camel",
  "🦒": "girafa giraffe",
  "🐎": "cavalo horse",
  "🐖": "porco pig",
  "🐑": "ovelha ewe sheep",
  "🐐": "cabra goat bode",
  "🦌": "cervo deer veado",
  "🐕": "cachorro dog",
  "🐩": "poodle cachorro dog",
  "🐈": "gato cat",
  "🐓": "galo rooster",
  "🦚": "pavão peacock",
  "🦜": "papagaio parrot",
  "🦢": "cisne swan",
  "🦩": "flamingo",
  "🐇": "coelho rabbit",
  "🦔": "ouriço hedgehog porco espinho",
  "❤️": "coração vermelho red heart amor love",
  "🧡": "coração laranja orange heart",
  "💛": "coração amarelo yellow heart",
  "💚": "coração verde green heart",
  "💙": "coração azul blue heart",
  "💜": "coração roxo purple heart",
  "🖤": "coração preto black heart",
  "🤍": "coração branco white heart",
  "🤎": "coração marrom brown heart",
  "💔": "coração partido broken heart",
  "💕": "dois corações two hearts",
  "💞": "corações girando revolving hearts",
  "💓": "coração batendo beating heart",
  "💗": "coração crescendo growing heart",
  "💖": "coração brilhando sparkling heart",
  "💘": "coração flecha arrow heart cupido cupid",
  "💝": "coração fita ribbon heart presente gift",
  "⭐": "estrela star",
  "🌟": "estrela brilhando glowing star",
  "✨": "brilho sparkles faísca",
  "⚡": "raio lightning high voltage energia energy",
  "🔥": "fogo fire chama flame quente hot",
  "💥": "explosão collision boom",
  "🎉": "festa party popper comemoração celebration",
  "🎊": "confete confetti festa party",
  "🎈": "balão balloon festa party",
  "🎯": "alvo bullseye target meta goal",
  "🎮": "jogo game videogame controle controller",
  "🎲": "dado dice game jogo",
  "🎵": "nota musical note música music",
  "🎶": "notas musicais notes música music",
  "🎸": "guitarra guitar violão música music",
  "🎹": "piano teclado keyboard música music",
  "🎺": "trompete trumpet música music",
  "🎻": "violino violin música music",
  "🥁": "tambor drum bateria música music",
  "🎤": "microfone microphone karaokê cantar sing",
  "💻": "notebook laptop computador computer",
  "📱": "celular mobile phone telefone smartphone",
  "💡": "lâmpada light bulb ideia idea",
  "🔑": "chave key",
  "🔒": "cadeado locked trancado segurança security",
  "📚": "livros books estudo study",
  "📖": "livro aberto open book leitura reading",
  "✏️": "lápis pencil escrever write",
  "📝": "memo nota note escrever write",
  "📌": "alfinete pushpin pin",
  "📎": "clipe paperclip",
  "📊": "gráfico barras bar chart",
  "📈": "gráfico subindo chart increasing crescendo",
  "📉": "gráfico descendo chart decreasing caindo",
  "🚀": "foguete rocket lançamento launch",
  "✈️": "avião airplane viagem travel",
  "🚗": "carro car automóvel automobile",
  "🚕": "táxi taxi cab",
  "🚙": "suv carro car",
  "🏠": "casa house lar home",
  "🏢": "prédio office building escritório",
  "🏰": "castelo castle",
  "🌍": "globo globe mundo world terra earth europa africa",
  "🌎": "globo globe mundo world terra earth americas",
  "🌏": "globo globe mundo world terra earth ásia asia",
  "🌈": "arco-íris rainbow",
  "☀️": "sol sun",
  "🌙": "lua moon crescente crescent",
  "☁️": "nuvem cloud",
  "🍕": "pizza",
  "🍔": "hambúrguer hamburger burger",
  "🍟": "batata frita french fries",
  "🌭": "cachorro quente hot dog",
  "🍿": "pipoca popcorn",
  "🍳": "ovo frito cooking cozinhando",
  "🍗": "frango chicken perna leg",
  "🍖": "carne meat osso bone",
  "🌮": "taco mexicano",
  "🌯": "burrito",
  "🍝": "espaguete spaghetti macarrão pasta",
  "🍜": "ramen sopa noodles",
  "🍲": "panela pot comida food",
  "🍣": "sushi japonês japanese",
  "🍱": "bentô bento box japonês",
  "🍩": "donut rosquinha doughnut",
  "🍪": "biscoito cookie",
  "🎂": "bolo aniversário birthday cake",
  "🍰": "bolo fatia shortcake slice",
  "🧁": "cupcake bolinho",
  "🍫": "chocolate bar barra",
  "🍬": "bala candy doce sweet",
  "🍭": "pirulito lollipop",
  "🍯": "mel honey pote pot",
  "☕": "café coffee chá tea bebida quente hot beverage",
  "🍵": "chá tea xícara cup",
  "🍺": "cerveja beer chopp",
  "🍻": "cerveja brinde beer cheers",
  "🥂": "brinde cheers taça champagne clinking glasses",
  "🍷": "vinho wine taça glass",
  "🍾": "champagne garrafa bottle",
  "👍": "joinha thumbs up legal like positivo",
  "👎": "thumbs down negativo dislike",
  "👊": "soco fist punch",
  "✊": "punho raised fist força strength",
  "👏": "palmas clapping aplausos",
  "🙌": "mãos levantadas raising hands celebração",
  "🙏": "oração pray mãos juntas folded hands obrigado thanks",
  "✌️": "paz peace vitória victory",
  "👋": "acenando waving tchau bye olá hello",
  "💪": "bíceps flexed muscle forte strong força",
  "🏆": "troféu trophy campeão champion",
  "🥇": "ouro gold primeiro first medalha medal",
  "🥈": "prata silver segundo second medalha",
  "🥉": "bronze terceiro third medalha",
  "🏅": "medalha esportes sports medal",
  "🎨": "arte art paleta palette pintura painting",
  "🎬": "cinema clapper board filme movie",
  "🎧": "fone headphone música music ouvindo listening",
  "🩺": "estetoscópio stethoscope médico doctor saúde health",
  "🧠": "cérebro brain mente mind inteligência intelligence",
  "💼": "maleta briefcase trabalho work negócio business",
  "💰": "dinheiro money bag saco",
  "🍽️": "garfo faca prato fork knife plate",
  "🍎": "maçã vermelha red apple fruta fruit",
  "🍏": "maçã verde green apple fruta fruit",
  "🍊": "tangerina laranja orange",
  "🍋": "limão lemon",
  "🍌": "banana",
  "🍉": "melancia watermelon",
  "🍇": "uva grapes",
  "🍓": "morango strawberry",
  "🍒": "cereja cherries",
  "🍑": "pêssego peach",
  "🍍": "abacaxi pineapple",
  "🥝": "kiwi fruta fruit",
  "🍅": "tomate tomato",
  "🍆": "berinjela eggplant",
  "🥑": "abacate avocado",
  "🥦": "brócolis broccoli",
  "🌽": "milho corn espiga",
  "🥕": "cenoura carrot",
  "🧀": "queijo cheese",
  "🍞": "pão bread",
  "🥐": "croissant",
  "🍤": "camarão shrimp frito fried",
  "🍧": "raspadinha shaved ice",
  "🍨": "sorvete ice cream",
  "🍦": "sorvete casquinha soft ice cream",
  "🍮": "pudim custard",
  "🍶": "saquê sake",
  "🍸": "coquetel cocktail",
  "🍹": "tropical drink bebida",
  "🧊": "gelo ice cubo",
  "🤏": "beliscando pinching pequeno small",
  "👈": "apontando esquerda pointing left",
  "👉": "apontando direita pointing right",
  "👆": "apontando cima pointing up",
  "👇": "apontando baixo pointing down",
  "☝️": "apontando cima index pointing up",
  "✋": "mão levantada raised hand pare stop",
  "🖖": "vulcano vulcan salute spock",
  "🤙": "me liga call me hang loose",
  "🖕": "dedo meio middle finger",
  "👶": "bebê baby criança child",
  "💃": "dançando dancing mulher woman",
  "🕺": "dançando dancing homem man",
  "🏁": "bandeira quadriculada checkered flag corrida race",
  "🚩": "bandeira vermelha red flag triangular",
  "🇧🇷": "brasil brazil bandeira flag",
  "🎁": "presente gift wrapped embrulho",
  "🎀": "laço ribbon fita",
  "🎆": "fogos artifício fireworks",
  "🎇": "vela sparkler faísca",
  "🎃": "abóbora pumpkin halloween jack lantern",
  "🎄": "árvore natal christmas tree",
  "🔮": "bola cristal crystal ball magia magic",
  "🌸": "flor cerejeira cherry blossom sakura",
  "🌹": "rosa rose flor flower",
  "🌺": "hibisco hibiscus flor flower",
  "🌻": "girassol sunflower flor flower",
  "🌼": "flor blossom",
  "🌷": "tulipa tulip flor flower",
  "🌱": "broto seedling planta plant",
  "🌲": "pinheiro evergreen tree árvore",
  "🌳": "árvore deciduous tree",
  "🌴": "palmeira palm tree",
  "🌵": "cacto cactus",
  "🍀": "trevo four leaf clover sorte luck",
  "🍁": "folha maple leaf bordo outono autumn",
  "🍂": "folhas caídas fallen leaf outono autumn",
  "🍃": "folha wind vento",
  "🍄": "cogumelo mushroom",
  "🌊": "onda wave mar sea oceano ocean",
  "💐": "buquê bouquet flores flowers",
  "🌚": "lua nova new moon face",
  "🌝": "lua cheia full moon face",
  "🌞": "sol face sun rosto",
  "❄️": "neve snowflake flocos frio cold inverno winter",
  "☃️": "boneco neve snowman inverno winter",
  "⛄": "boneco neve snowman",
  "⚽": "futebol soccer bola ball",
  "🏀": "basquete basketball bola ball",
  "🏈": "futebol americano football bola ball",
  "⚾": "beisebol baseball bola ball",
  "🎾": "tênis tennis bola ball",
  "🏐": "vôlei volleyball bola ball",
  "🎱": "sinuca bilhar pool 8 ball",
  "🏓": "pingue pongue ping pong table tennis",
  "🏸": "badminton",
  "🥊": "boxe boxing luva glove",
  "🥋": "artes marciais martial arts judô karatê",
  "🎿": "esqui ski neve snow",
  "⌨️": "teclado keyboard",
  "🖥️": "desktop computador computer monitor",
  "🔍": "lupa search busca magnifying glass pesquisa",
  "🔬": "microscópio microscope ciência science",
  "🔭": "telescópio telescope astronomia astronomy",
  "💾": "disquete floppy disk salvar save",
  "📷": "câmera camera foto photo",
  "📹": "filmadora video camera",
  "📺": "televisão television tv",
  "📻": "rádio radio",
  "🔧": "chave inglesa wrench ferramenta tool",
  "🔨": "martelo hammer ferramenta tool",
  "⚙️": "engrenagem gear configuração settings",
  "💊": "pílula pill remédio medicine",
  "🧬": "dna genética genetics ciência science",
  "🧪": "tubo ensaio test tube ciência science",
  "👑": "coroa crown rei king rainha queen",
  "🎩": "cartola top hat chapéu",
  "💎": "diamante gem stone joia jewel",
  "💍": "anel ring casamento wedding",
  "👓": "óculos glasses",
  "🕶️": "óculos sol sunglasses",
  "🏍️": "moto motorcycle motocicleta",
  "🛵": "scooter moto",
  "🚲": "bicicleta bicycle bike",
  "🚂": "locomotiva locomotive trem train",
  "🛳️": "navio ship cruise cruzeiro",
  "⛵": "veleiro sailboat barco boat",
  "🏡": "casa jardim house garden lar home",
  "🏥": "hospital saúde health",
  "🏦": "banco bank dinheiro money",
  "🏪": "loja store conveniência convenience",
  "🏫": "escola school educação education",
  "🏭": "fábrica factory indústria industry",
  "🏯": "castelo japonês japanese castle",
  "⛪": "igreja church religião religion",
  // New additions
  "🫠": "derretendo melting dissolving",
  "🫡": "saudação saluting continência",
  "🫢": "mão boca surpreso hand mouth surprised",
  "🫣": "espiando peeking olhando peek",
  "🫤": "boca diagonal diagonal mouth insatisfeito",
  "🫥": "linha pontilhada dotted line invisível invisible",
  "🫨": "tremendo shaking vibrando",
  "😵‍💫": "tonto espiral spiral dizzy",
  "🥸": "disfarce disguised bigode mustache",
  "🥹": "segurando lágrima holding back tears emocionado emotional",
  "☹️": "triste frowning sad",
  "☠️": "caveira ossos skull crossbones morte death",
  "🫶": "mãos coração heart hands amor love",
  "🐻‍❄️": "urso polar bear white branco",
  "🐽": "nariz porco pig nose",
  "🐤": "pintinho baby chick passarinho",
  "🐣": "pintinho nascendo hatching chick ovo egg",
  "🐥": "pintinho frente chick front",
  "🐗": "javali boar wild pig",
  "🪱": "minhoca worm verme",
  "🐛": "inseto bug bicho",
  "🪰": "mosca fly inseto",
  "🪲": "besouro beetle inseto",
  "🪳": "barata cockroach inseto nojo",
  "🦂": "escorpião scorpion",
  "🕷️": "aranha spider",
  "🕸️": "teia aranha spider web",
  "🦑": "lula squid",
  "🦐": "camarão shrimp",
  "🦀": "caranguejo crab siri",
  "🐠": "peixe tropical fish",
  "🐟": "peixe fish",
  "🐡": "baiacu blowfish peixe",
  "🦓": "zebra",
  "🦧": "orangotango orangutan",
  "🦛": "hipopótamo hippopotamus hippo",
  "🦏": "rinoceronte rhinoceros rhino",
  "🐫": "camelo two humps dromedário",
  "🦘": "canguru kangaroo",
  "🦬": "bisão bison búfalo buffalo",
  "🐃": "búfalo water buffalo",
  "🐂": "boi ox",
  "🐄": "vaca cow",
  "🐏": "carneiro ram ovelha",
  "🦙": "lhama llama alpaca",
  "🦮": "cão guia guide dog",
  "🐈‍⬛": "gato preto black cat",
  "🦃": "peru turkey",
  "🕊️": "pomba dove paz peace",
  "🦝": "guaxinim raccoon",
  "🦨": "gambá skunk",
  "🦡": "texugo badger",
  "🦫": "castor beaver",
  "🦦": "lontra otter",
  "🦥": "preguiça sloth",
  "🐁": "rato mouse pequeno small",
  "🐀": "rato rat ratazana",
  "🐿️": "esquilo chipmunk",
  "🪶": "pena feather",
  "🦤": "dodô dodo extinto extinct",
  "🦭": "foca seal",
  "🐉": "dragão dragon",
  "🐲": "dragão face dragon cara",
  "🦕": "dinossauro sauropod dinosaur brontossauro",
  "🦖": "t-rex tiranossauro dinosaur dinossauro",
  "🏵️": "roseta rosette flor flower",
  "🥀": "flor murcha wilted flower",
  "🪻": "jacinto hyacinth flor flower",
  "🪴": "planta vaso potted plant",
  "🌾": "arroz sheaf rice trigo wheat",
  "🌿": "erva herb planta plant",
  "☘️": "trevo shamrock sorte luck",
  "🪹": "ninho vazio empty nest",
  "🪺": "ninho ovos nest eggs",
  "🐚": "concha shell espiral spiral",
  "🪸": "coral reef",
  "🪨": "pedra rock rocha stone",
  "🪷": "lótus lotus flor flower",
  "❤️‍🔥": "coração fogo heart fire paixão passion",
  "❤️‍🩹": "coração curando mending heart",
  "❣️": "coração exclamação heart exclamation",
  "💟": "decoração coração heart decoration",
  "♥️": "coração naipe heart suit",
  "💑": "casal coração couple heart amor love",
  "💏": "beijo kiss amor love",
  "💋": "marca beijo kiss mark batom lipstick",
  "💫": "tonto dizzy estrela star",
  "💦": "gotas suor sweat droplets água water",
  "💨": "correndo dashing away vento wind rápido fast",
  "⛅": "sol nuvem sun cloud",
  "🌤️": "sol nuvem pequena sun small cloud",
  "🌥️": "sol nuvem grande sun large cloud",
  "🌦️": "sol chuva sun rain",
  "🌧️": "nuvem chuva cloud rain",
  "🌩️": "nuvem raio cloud lightning trovão thunder",
  "🌪️": "tornado furacão hurricane",
  "🌫️": "névoa fog neblina mist",
  "🧨": "rojão firecracker fogos",
  "🎋": "tanabata árvore tree",
  "🎍": "decoração pinheiro pine decoration",
  "🎎": "bonecas japonesas Japanese dolls",
  "🎏": "bandeira carpa carp streamer",
  "🎐": "sino vento wind chime",
  "🧧": "envelope vermelho red envelope chinês chinese",
  "🪅": "piñata festa party",
  "🪄": "varinha mágica magic wand",
  "🧿": "olho grego nazar amulet proteção protection",
  "🎑": "lua cerimônia moon ceremony",
  "🥎": "softball bola ball",
  "🏉": "rugby bola ball",
  "🥏": "disco frisbee flying disc",
  "🪀": "ioiô yo-yo brinquedo toy",
  "🏒": "hóquei gelo ice hockey",
  "🥍": "lacrosse",
  "🏑": "hóquei campo field hockey",
  "🥅": "gol rede goal net",
  "⛳": "golfe golf buraco hole",
  "🪁": "pipa kite",
  "🏹": "arco flecha bow arrow",
  "🎣": "pesca fishing vara pole",
  "🤿": "mergulho diving máscara mask",
  "⛷️": "esquiador skier neve snow",
  "🏂": "snowboard neve snow",
  "🏋️": "levantamento peso lifting weights academia gym",
  "🤸": "cambalhota cartwheeling ginástica gymnastics",
  "🛹": "skate skateboard",
  "🛼": "patins roller skate",
  "🏄": "surfe surfing onda wave",
  "🚣": "remando rowing barco boat",
  "🧗": "escalando climbing montanha mountain",
  "🏇": "corrida cavalos horse racing jóquei jockey",
  "🧩": "quebra-cabeça puzzle peça piece",
  "🪘": "tambor longo long drum",
  "🎷": "saxofone saxophone música music",
  "🪗": "acordeão accordion sanfona",
  "🪕": "banjo",
  "🪈": "flauta flute",
  "🖨️": "impressora printer",
  "🖱️": "mouse computador computer",
  "🗝️": "chave antiga old key vintage",
  "🔓": "destrancado unlocked aberto open",
  "📕": "livro fechado closed book vermelho red",
  "📗": "livro verde green book",
  "📘": "livro azul blue book",
  "📙": "livro laranja orange book",
  "📓": "caderno notebook",
  "📔": "caderno decorado notebook decorative",
  "📒": "livro contábil ledger",
  "📍": "alfinete redondo round pushpin",
  "🖇️": "clipes linked paperclips",
  "✂️": "tesoura scissors cortar cut",
  "🗂️": "divisórias card index dividers pasta",
  "📁": "pasta folder arquivo file",
  "📂": "pasta aberta open folder",
  "🗒️": "bloco notas spiral notepad",
  "📋": "prancheta clipboard",
  "🔎": "lupa direita magnifying glass right",
  "📡": "antena satellite parabólica",
  "💿": "cd disco optical disk",
  "📀": "dvd disco",
  "📸": "câmera flash camera",
  "🎥": "câmera cinema movie camera",
  "⚒️": "martelo picareta hammer pick",
  "🛠️": "martelo chave hammer wrench ferramentas tools",
  "⛏️": "picareta pick mineração mining",
  "🪚": "serra saw carpintaria carpentry",
  "🔩": "parafuso porca nut bolt",
  "🧰": "caixa ferramentas toolbox",
  "⛓️": "corrente chains",
  "🪝": "gancho hook",
  "🩹": "band-aid curativo bandage",
  "🧫": "placa petri dish laboratório lab",
  "🧹": "vassoura broom limpar clean",
  "🪣": "balde bucket",
  "🧴": "loção lotion frasco bottle",
  "🛒": "carrinho compras shopping cart mercado market",
  "🎒": "mochila backpack escola school",
  "🪑": "cadeira chair assento seat",
  "🛋️": "sofá couch lamp sala living",
  "🛏️": "cama bed dormir sleep",
  "🪞": "espelho mirror reflexo reflection",
  "🪟": "janela window",
  "🚪": "porta door entrada entrance",
  "🔔": "sino bell notificação notification",
  "🔕": "sino silenciado muted bell",
  "📯": "corneta postal horn",
  "🗑️": "lixeira wastebasket trash lixo",
  "📦": "pacote package caixa box entrega delivery",
  "🏷️": "etiqueta label tag preço price",
  "💴": "nota iene yen banknote dinheiro money",
  "💵": "nota dólar dollar banknote dinheiro money",
  "💶": "nota euro banknote dinheiro money",
  "💷": "nota libra pound banknote dinheiro money",
  "💸": "dinheiro voando money wings gastando spending",
  "💳": "cartão crédito credit card pagamento payment",
  "🪙": "moeda coin dinheiro money",
  "⏰": "despertador alarm clock relógio",
  "⌚": "relógio watch pulso wrist",
  "⏳": "ampulheta hourglass tempo time",
  "⌛": "ampulheta hourglass done tempo time",
  "🔋": "bateria battery energia energy",
  "🔌": "tomada plug elétrico electric",
  "🥽": "óculos proteção goggles",
  "👗": "vestido dress roupa clothes",
  "👘": "kimono quimono japonês japanese",
  "👙": "biquíni bikini praia beach",
  "👚": "blusa roupa mulher woman clothes",
  "👛": "bolsa purse carteira",
  "👜": "bolsa handbag",
  "👝": "clutch bolsa bag",
  "🎽": "camisa corrida running shirt esporte sport",
  "🩱": "maiô swimsuit",
  "🩲": "cueca briefs roupa íntima underwear",
  "🩳": "shorts bermuda",
  "👔": "gravata necktie formal",
  "👕": "camiseta t-shirt roupa clothes",
  "👖": "jeans calça pants",
  "🧣": "cachecol scarf inverno winter",
  "🧤": "luvas gloves inverno winter",
  "🧥": "casaco coat jaqueta jacket",
  "🧦": "meias socks",
  "👞": "sapato homem man shoe formal",
  "👟": "tênis running shoe esporte sport",
  "👠": "salto alto high heel sapato shoe",
  "👡": "sandália sandal",
  "🩴": "chinelo thong sandal flip flop",
  "👢": "bota boot",
  "👒": "chapéu mulher woman hat",
  "🪖": "capacete militar military helmet",
  "⛑️": "capacete resgate rescue helmet",
  "🛸": "disco voador flying saucer ufo ovni",
  "🚌": "ônibus bus",
  "🚎": "trólebus trolleybus",
  "🏎️": "carro corrida racing car fórmula",
  "🚓": "carro polícia police car",
  "🚑": "ambulância ambulance",
  "🚒": "caminhão bombeiros fire engine",
  "🚐": "van minibus",
  "🛻": "picape pickup truck caminhonete",
  "🚚": "caminhão entrega delivery truck",
  "🚛": "caminhão articulado lorry",
  "🚜": "trator tractor fazenda farm",
  "🛺": "tuk-tuk auto rickshaw",
  "🛴": "patinete kick scooter",
  "🚆": "trem train",
  "🚇": "metrô metro subway",
  "🚈": "trem leve light rail",
  "🚝": "monotrilho monorail",
  "🚄": "trem bala high-speed train shinkansen",
  "⛴️": "balsa ferry barco boat",
  "🛥️": "lancha motor boat",
  "🚤": "lancha speedboat rápido fast",
  "🚢": "navio grande ship",
  "🛶": "canoa canoe caiaque kayak",
  "🚁": "helicóptero helicopter",
  "🛩️": "avião pequeno small airplane",
  "🏣": "correio japonês japanese post office",
  "🏤": "correio post office",
  "🏨": "hotel hospedagem",
  "🏩": "hotel amor love hotel",
  "🏬": "shopping department store loja",
  "💒": "casamento wedding capela chapel",
  "🗼": "torre tokyo tower",
  "🗽": "estátua liberdade statue liberty",
  "🕌": "mesquita mosque",
  "🛕": "templo hindu temple",
  "🕍": "sinagoga synagogue",
  "⛩️": "portal shinto shrine torii",
  "🗻": "monte fuji mount",
  "🏔️": "montanha neve snow mountain",
  "⛺": "barraca tent acampar camping",
  "🏕️": "camping acampamento",
  "🎡": "roda gigante ferris wheel parque park",
  "🎢": "montanha russa roller coaster parque park",
  "🎠": "carrossel carousel cavalo horse",
  "⛲": "fonte fountain",
  "🗺️": "mapa mundo world map",
  "🧂": "sal salt tempero seasoning",
  "🥚": "ovo egg",
  "🥞": "panqueca pancakes café manhã breakfast",
  "🧇": "waffle café manhã breakfast",
  "🥓": "bacon",
  "🥩": "carne meat bife steak",
  "🥙": "pão sírio flatbread",
  "🧆": "falafel",
  "🥗": "salada salad verde green saudável healthy",
  "🥘": "panela rasa shallow pan paella",
  "🍛": "curry arroz rice",
  "🥟": "bolinho dumpling gyoza",
  "🦪": "ostra oyster marisco",
  "🍙": "onigiri rice ball arroz",
  "🍚": "arroz cozido cooked rice",
  "🍘": "biscoito arroz rice cracker",
  "🍥": "bolinho peixe fish cake kamaboko naruto",
  "🥠": "biscoito sorte fortune cookie",
  "🥮": "bolo lua moon cake",
  "🍢": "oden espeto skewer",
  "🍡": "dango mochi doce",
  "🥧": "torta pie",
  "🌰": "castanha chestnut noz nut",
  "🥜": "amendoim peanuts",
  "🥛": "leite milk copo glass",
  "🍼": "mamadeira baby bottle bebê",
  "🫖": "bule teapot chá tea",
  "🧃": "caixinha suco juice box bebida beverage",
  "🥤": "copo canudo cup straw refrigerante soda",
  "🧋": "bubble tea boba chá",
  "🥃": "copo whisky tumbler glass",
  "🫗": "derramando pouring líquido liquid",
  "🍐": "pêra pear fruta fruit",
  "🫐": "mirtilo blueberries fruta fruit",
  "🍈": "melão melon fruta fruit",
  "🥭": "manga mango fruta fruit",
  "🥥": "coco coconut",
  "🫛": "ervilha pea pod vagem",
  "🥬": "folha verde leafy green alface lettuce",
  "🥒": "pepino cucumber",
  "🌶️": "pimenta hot pepper picante spicy",
  "🫑": "pimentão bell pepper",
  "🧄": "alho garlic",
  "🧅": "cebola onion",
  "🥔": "batata potato",
  "🍠": "batata doce sweet potato",
  "🫚": "gengibre ginger",
  "🥯": "bagel pão bread",
  "🥖": "baguete baguette pão bread francês french",
  "🥨": "pretzel",
  "🥪": "sanduíche sandwich lanche snack",
  "🫔": "tamale mexicano mexican",
  "🤛": "soco esquerda left fist",
  "🤜": "soco direita right fist",
  "🤲": "palmas cima palms up juntas together",
  "🤝": "aperto mão handshake acordo deal",
  "🤞": "dedos cruzados crossed fingers sorte luck",
  "🫰": "dedo polegar cruzado finger thumb crossed",
  "🤟": "te amo love you gesto gesture",
  "🤘": "rock chifres horns metal",
  "👌": "ok okay perfeito perfect",
  "🤌": "dedos juntos pinched fingers italiano italian",
  "🤚": "mão costas raised back hand",
  "🖐️": "mão dedos abertos hand fingers splayed",
  "🫳": "palma baixo palm down",
  "🫴": "palma cima palm up",
  "🦾": "braço mecânico mechanical arm robô robot",
  "✍️": "escrevendo writing mão hand",
  "🫵": "apontando viewer apontando você pointing you",
  "🤳": "selfie foto photo celular phone",
  "👧": "menina girl criança child",
  "🧒": "criança child",
  "👦": "menino boy criança child",
  "👩": "mulher woman",
  "🧑": "pessoa person",
  "👨": "homem man",
  "👵": "senhora idosa old woman avó grandmother",
  "🧓": "pessoa idosa older person",
  "👴": "senhor idoso old man avô grandfather",
  "🧑‍🎄": "papai mamãe noel mx claus natal christmas",
  "🎅": "papai noel santa claus natal christmas",
  "🤶": "mamãe noel mrs claus natal christmas",
  "🧙": "mago mage bruxo wizard",
  "🧚": "fada fairy",
  "🧛": "vampiro vampire",
  "🧜": "sereia merman merperson",
  "🧝": "elfo elf",
  "🦸": "herói superhero super",
  "🦹": "vilão supervillain super",
  "🧞": "gênio genie lâmpada lamp",
  "🧟": "zumbi zombie morto dead",
  "🤷": "sei não shrugging encolher ombros",
  "🤦": "facepalm mão rosto palm face",
  "🙋": "mão levantada raising hand",
  "🙇": "reverência bowing curvando",
  "🧑‍💻": "programador technologist dev tech",
  "🧑‍🎨": "artista artist",
  "🧑‍🚀": "astronauta astronaut espaço space",
  "🧑‍🔬": "cientista scientist",
  "🧑‍🍳": "cozinheiro cook chef",
  "🧑‍🎓": "estudante student formatura graduation",
  "🧑‍🏫": "professor teacher",
  "🧑‍⚕️": "médico doctor saúde health",
  "🧑‍🌾": "fazendeiro farmer agricultor",
  "🧑‍🔧": "mecânico mechanic",
  "🧑‍💼": "escritório office worker executivo",
  "🧑‍🚒": "bombeiro firefighter",
  "🎖️": "medalha militar military medal",
  "🎌": "bandeiras cruzadas crossed flags",
  "🏴": "bandeira preta black flag",
  "🏳️": "bandeira branca white flag paz peace rendição surrender",
  "🏳️‍🌈": "bandeira arco-íris rainbow flag lgbtq pride orgulho",
  "🏳️‍⚧️": "bandeira trans transgender flag",
  "🏴‍☠️": "bandeira pirata pirate flag",
  "🇺🇸": "estados unidos united states eua usa bandeira flag américa america",
  "🇯🇵": "japão japan bandeira flag",
  "🇰🇷": "coreia sul south korea bandeira flag",
  "🇬🇧": "reino unido united kingdom uk bandeira flag inglaterra england",
  "🇫🇷": "frança france bandeira flag",
  "🇩🇪": "alemanha germany bandeira flag",
  "🇮🇹": "itália italy bandeira flag",
  "🇪🇸": "espanha spain bandeira flag",
  "🇵🇹": "portugal bandeira flag",
  "🇦🇷": "argentina bandeira flag",
  "🇲🇽": "méxico mexico bandeira flag",
  "♻️": "reciclagem recycling símbolo symbol",
  "⚠️": "aviso warning atenção attention perigo danger",
  "🚫": "proibido prohibited não no",
  "❌": "errado wrong cross mark não no",
  "⭕": "círculo vermelho red circle",
  "✅": "correto check mark certo right",
  "☑️": "check box verificado checked",
  "❓": "pergunta question mark dúvida",
  "❗": "exclamação exclamation mark importante important",
  "‼️": "dupla exclamação double exclamation",
  "⁉️": "exclamação pergunta exclamation question",
  "💤": "dormindo zzz sono sleep",
  "💬": "balão fala speech balloon conversa chat",
  "💭": "balão pensamento thought balloon",
  "🗯️": "balão raiva anger bubble",
  "♾️": "infinito infinity eterno eternal",
  "🔊": "alto volume speaker high som sound",
  "🔇": "mudo muted speaker silêncio silence",
  "📢": "alto falante loudspeaker",
  "📣": "megafone megaphone",
  "🪩": "bola espelho mirror ball disco",
  "🎗️": "fita lembrete reminder ribbon",
  "🎟️": "ingresso admission tickets",
  "🎫": "bilhete ticket ingresso",
  "🧸": "ursinho teddy bear pelúcia",
  "🖼️": "quadro framed picture moldura frame",
  "🛍️": "sacolas compras shopping bags",
  "📿": "terço prayer beads rosário",
  "🔗": "link corrente",
  "🪪": "identidade identification card documento document",
  "📮": "caixa correio postbox",
  "✉️": "envelope carta letter",
  "📧": "email e-mail",
  "📩": "envelope seta arrow",
  "📨": "envelope recebido incoming",
  "🗓️": "calendário espiral spiral calendar",
  "📅": "calendário calendar data date",
  "📆": "calendário arrancar tear-off calendar",
  "♈": "áries aries zodíaco zodiac",
  "♉": "touro taurus zodíaco zodiac",
  "♊": "gêmeos gemini zodíaco zodiac",
  "♋": "câncer cancer zodíaco zodiac",
  "♌": "leão leo zodíaco zodiac",
  "♍": "virgem virgo zodíaco zodiac",
  "♎": "libra zodíaco zodiac balança",
  "♏": "escorpião scorpio zodíaco zodiac",
  "♐": "sagitário sagittarius zodíaco zodiac",
  "♑": "capricórnio capricorn zodíaco zodiac",
  "♒": "aquário aquarius zodíaco zodiac",
  "♓": "peixes pisces zodíaco zodiac",
};

interface EmojiPickerProps {
  emojis: string[];
  onSelect: (emoji: string) => void;
}

export function EmojiPicker({ emojis, onSelect }: EmojiPickerProps) {
  const [search, setSearch] = useState("");

  const filtered = useMemo(() => {
    if (!search.trim()) return emojis;
    const q = search.toLowerCase().trim();
    return emojis.filter((em) => {
      const keywords = EMOJI_KEYWORDS[em];
      if (keywords && keywords.toLowerCase().includes(q)) return true;
      return em.includes(q);
    });
  }, [emojis, search]);

  return (
    <div className="space-y-2">
      <div className="relative">
        <Search className="absolute left-2 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Pesquisar emoji..."
          className="w-full rounded-md border border-border bg-secondary pl-7 pr-2 py-1.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-accent"
          autoFocus
        />
      </div>
      <div className="grid grid-cols-8 gap-0.5 max-h-48 overflow-y-auto">
        {filtered.length === 0 ? (
          <div className="col-span-8 py-4 text-center text-xs text-muted-foreground">Nenhum emoji encontrado</div>
        ) : (
          filtered.map((em, i) => (
            <button
              key={i}
              onClick={() => onSelect(em)}
              className="flex h-8 w-8 items-center justify-center rounded-md hover:bg-secondary transition-colors text-xl"
            >
              {em}
            </button>
          ))
        )}
      </div>
    </div>
  );
}
