import { memo } from "react";

/**
 * Renders Microsoft Fluent Emoji (3D style) as images from GitHub CDN.
 * Falls back to native emoji if not mapped or image fails to load.
 */

const CDN_BASE = "https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets";

const EMOJI_MAP: Record<string, { folder: string; file: string }> = {};

function reg(emoji: string, folder: string, file?: string) {
  EMOJI_MAP[emoji] = {
    folder,
    file: file || folder.toLowerCase().replace(/ /g, "_") + "_3d.png",
  };
}

// ── Smileys & Emotion ──
reg("😀", "Grinning face");
reg("😃", "Grinning face with big eyes");
reg("😄", "Grinning face with smiling eyes");
reg("😁", "Beaming face with smiling eyes");
reg("😆", "Grinning squinting face");
reg("😅", "Grinning face with sweat");
reg("🤣", "Rolling on the floor laughing");
reg("😂", "Face with tears of joy");
reg("🙂", "Slightly smiling face");
reg("🙃", "Upside-down face");
reg("😉", "Winking face");
reg("😊", "Smiling face with smiling eyes");
reg("😇", "Smiling face with halo");
reg("🥰", "Smiling face with hearts");
reg("😍", "Smiling face with heart-eyes");
reg("🤩", "Star-struck");
reg("😘", "Face blowing a kiss");
reg("😗", "Kissing face");
reg("😚", "Kissing face with closed eyes");
reg("😙", "Kissing face with smiling eyes");
reg("🥲", "Smiling face with tear");
reg("😋", "Face savoring food");
reg("😛", "Face with tongue");
reg("😜", "Winking face with tongue");
reg("🤪", "Zany face");
reg("😝", "Squinting face with tongue");
reg("🤑", "Money-mouth face");
reg("🤗", "Smiling face with open hands", "hugging_face_3d.png");
reg("🤭", "Face with hand over mouth");
reg("🤫", "Shushing face");
reg("🤔", "Thinking face");
reg("🤐", "Zipper-mouth face");
reg("🤨", "Face with raised eyebrow");
reg("😐", "Neutral face");
reg("😑", "Expressionless face");
reg("😶", "Face without mouth");
reg("🫠", "Melting face");
reg("🫡", "Saluting face");
reg("🫢", "Face with open eyes and hand over mouth");
reg("🫣", "Face with peeking eye");
reg("🫤", "Face with diagonal mouth");
reg("🫥", "Dotted line face");
reg("😏", "Smirking face");
reg("😒", "Unamused face");
reg("🙄", "Face with rolling eyes");
reg("😬", "Grimacing face");
reg("🫨", "Shaking face");
reg("😌", "Relieved face");
reg("😔", "Pensive face");
reg("😪", "Sleepy face");
reg("🤤", "Drooling face");
reg("😴", "Sleeping face");
reg("😷", "Face with medical mask");
reg("🤒", "Face with thermometer");
reg("🤕", "Face with head-bandage");
reg("🤢", "Nauseated face");
reg("🤮", "Face vomiting");
reg("🥵", "Hot face");
reg("🥶", "Cold face");
reg("🥴", "Woozy face");
reg("😵", "Face with crossed-out eyes", "face_with_crossed-out_eyes_3d.png");
reg("😵‍💫", "Face with spiral eyes");
reg("🤯", "Exploding head");
reg("🤠", "Cowboy hat face");
reg("🥳", "Partying face");
reg("🥸", "Disguised face");
reg("😎", "Smiling face with sunglasses");
reg("🤓", "Nerd face");
reg("🧐", "Face with monocle");
reg("😕", "Confused face");
reg("🫤", "Face with diagonal mouth");
reg("😟", "Worried face");
reg("🙁", "Slightly frowning face");
reg("☹️", "Frowning face");
reg("😮", "Face with open mouth");
reg("😯", "Hushed face");
reg("😲", "Astonished face");
reg("😳", "Flushed face");
reg("🥺", "Pleading face");
reg("🥹", "Face holding back tears");
reg("😦", "Frowning face with open mouth");
reg("😧", "Anguished face");
reg("😨", "Fearful face");
reg("😰", "Anxious face with sweat");
reg("😥", "Sad but relieved face");
reg("😢", "Crying face");
reg("😭", "Loudly crying face");
reg("😱", "Face screaming in fear");
reg("😖", "Confounded face");
reg("😣", "Persevering face");
reg("😞", "Disappointed face");
reg("😓", "Downcast face with sweat");
reg("😩", "Weary face");
reg("😫", "Tired face");
reg("🥱", "Yawning face");
reg("😤", "Face with steam from nose");
reg("😡", "Enraged face", "pouting_face_3d.png");
reg("😠", "Angry face");
reg("🤬", "Face with symbols on mouth");
reg("😈", "Smiling face with horns");
reg("👿", "Angry face with horns");
reg("💀", "Skull");
reg("☠️", "Skull and crossbones");
reg("💩", "Pile of poo");
reg("🤡", "Clown face");
reg("👹", "Ogre");
reg("👺", "Goblin");
reg("👻", "Ghost");
reg("👽", "Alien");
reg("👾", "Alien monster");
reg("🤖", "Robot");
reg("🫶", "Heart hands");

// ── Cats ──
reg("😺", "Grinning cat");
reg("😸", "Grinning cat with smiling eyes");
reg("😹", "Cat with tears of joy");
reg("😻", "Smiling cat with heart-eyes");
reg("😼", "Cat with wry smile");
reg("😽", "Kissing cat");
reg("🙀", "Weary cat");
reg("😿", "Crying cat");
reg("😾", "Pouting cat");

// ── Monkeys ──
reg("🙈", "See-no-evil monkey");
reg("🙉", "Hear-no-evil monkey");
reg("🙊", "Speak-no-evil monkey");
reg("🐒", "Monkey");

// ── Animals ──
reg("🐶", "Dog face");
reg("🐱", "Cat face");
reg("🐭", "Mouse face");
reg("🐹", "Hamster");
reg("🐰", "Rabbit face");
reg("🦊", "Fox");
reg("🐻", "Bear");
reg("🐼", "Panda");
reg("🐻‍❄️", "Polar bear");
reg("🐨", "Koala");
reg("🐯", "Tiger face");
reg("🦁", "Lion");
reg("🐮", "Cow face");
reg("🐷", "Pig face");
reg("🐽", "Pig nose");
reg("🐸", "Frog");
reg("🐵", "Monkey face");
reg("🐔", "Chicken");
reg("🐧", "Penguin");
reg("🐦", "Bird");
reg("🐤", "Baby chick");
reg("🐣", "Hatching chick");
reg("🐥", "Front-facing baby chick");
reg("🦆", "Duck");
reg("🦅", "Eagle");
reg("🦉", "Owl");
reg("🦇", "Bat");
reg("🐺", "Wolf");
reg("🐗", "Boar");
reg("🐴", "Horse face");
reg("🦄", "Unicorn");
reg("🐝", "Honeybee");
reg("🪱", "Worm");
reg("🐛", "Bug");
reg("🦋", "Butterfly");
reg("🐌", "Snail");
reg("🐞", "Lady beetle");
reg("🐜", "Ant");
reg("🪰", "Fly");
reg("🪲", "Beetle");
reg("🪳", "Cockroach");
reg("🦂", "Scorpion");
reg("🕷️", "Spider");
reg("🕸️", "Spider web");
reg("🐢", "Turtle");
reg("🐍", "Snake");
reg("🦎", "Lizard");
reg("🐙", "Octopus");
reg("🦑", "Squid");
reg("🦐", "Shrimp");
reg("🦀", "Crab");
reg("🐠", "Tropical fish");
reg("🐟", "Fish");
reg("🐡", "Blowfish");
reg("🐬", "Dolphin");
reg("🐳", "Spouting whale");
reg("🐋", "Whale");
reg("🦈", "Shark");
reg("🐊", "Crocodile");
reg("🐅", "Tiger");
reg("🐆", "Leopard");
reg("🦓", "Zebra");
reg("🦍", "Gorilla");
reg("🦧", "Orangutan");
reg("🐘", "Elephant");
reg("🦛", "Hippopotamus");
reg("🦏", "Rhinoceros");
reg("🐪", "Camel");
reg("🐫", "Two-hump camel");
reg("🦒", "Giraffe");
reg("🦘", "Kangaroo");
reg("🦬", "Bison");
reg("🐃", "Water buffalo");
reg("🐂", "Ox");
reg("🐄", "Cow");
reg("🐎", "Horse");
reg("🐖", "Pig");
reg("🐏", "Ram");
reg("🐑", "Ewe");
reg("🦙", "Llama");
reg("🐐", "Goat");
reg("🦌", "Deer");
reg("🐕", "Dog");
reg("🐩", "Poodle");
reg("🦮", "Guide dog");
reg("🐈", "Cat");
reg("🐈‍⬛", "Black cat");
reg("🐓", "Rooster");
reg("🦃", "Turkey");
reg("🦚", "Peacock");
reg("🦜", "Parrot");
reg("🦢", "Swan");
reg("🦩", "Flamingo");
reg("🕊️", "Dove");
reg("🐇", "Rabbit");
reg("🦝", "Raccoon");
reg("🦨", "Skunk");
reg("🦡", "Badger");
reg("🦫", "Beaver");
reg("🦦", "Otter");
reg("🦥", "Sloth");
reg("🐁", "Mouse");
reg("🐀", "Rat");
reg("🐿️", "Chipmunk");
reg("🦔", "Hedgehog");
reg("🦇", "Bat");
reg("🪶", "Feather");
reg("🦤", "Dodo");
reg("🦭", "Seal");
reg("🐉", "Dragon");
reg("🐲", "Dragon face");
reg("🦕", "Sauropod");
reg("🦖", "T-Rex");

// ── Nature & Plants ──
reg("🌸", "Cherry blossom");
reg("🏵️", "Rosette");
reg("🌹", "Rose");
reg("🥀", "Wilted flower");
reg("🌺", "Hibiscus");
reg("🌻", "Sunflower");
reg("🌼", "Blossom");
reg("🌷", "Tulip");
reg("🪻", "Hyacinth");
reg("🌱", "Seedling");
reg("🪴", "Potted plant");
reg("🌲", "Evergreen tree");
reg("🌳", "Deciduous tree");
reg("🌴", "Palm tree");
reg("🌵", "Cactus");
reg("🌾", "Sheaf of rice");
reg("🌿", "Herb");
reg("☘️", "Shamrock");
reg("🍀", "Four leaf clover");
reg("🍁", "Maple leaf");
reg("🍂", "Fallen leaf");
reg("🍃", "Leaf fluttering in wind");
reg("🪹", "Empty nest");
reg("🪺", "Nest with eggs");
reg("🍄", "Mushroom");
reg("🐚", "Spiral shell");
reg("🪸", "Coral");
reg("🪨", "Rock");
reg("🌊", "Water wave");
reg("💐", "Bouquet");
reg("🪷", "Lotus");

// ── Hearts ──
reg("❤️", "Red heart");
reg("🧡", "Orange heart");
reg("💛", "Yellow heart");
reg("💚", "Green heart");
reg("💙", "Blue heart");
reg("💜", "Purple heart");
reg("🖤", "Black heart");
reg("🤍", "White heart");
reg("🤎", "Brown heart");
reg("❤️‍🔥", "Heart on fire");
reg("❤️‍🩹", "Mending heart");
reg("❣️", "Heart exclamation");
reg("💔", "Broken heart");
reg("💕", "Two hearts");
reg("💞", "Revolving hearts");
reg("💓", "Beating heart");
reg("💗", "Growing heart");
reg("💖", "Sparkling heart");
reg("💘", "Heart with arrow");
reg("💝", "Heart with ribbon");
reg("💟", "Heart decoration");
reg("♥️", "Heart suit");
reg("💑", "Couple with heart");
reg("💏", "Kiss");
reg("💋", "Kiss mark");

// ── Stars & Weather ──
reg("⭐", "Star");
reg("🌟", "Glowing star");
reg("✨", "Sparkles");
reg("⚡", "High voltage");
reg("🔥", "Fire");
reg("💥", "Collision");
reg("💫", "Dizzy");
reg("💦", "Sweat droplets");
reg("💨", "Dashing away");
reg("🌈", "Rainbow");
reg("☀️", "Sun");
reg("🌙", "Crescent moon");
reg("🌚", "New moon face");
reg("🌝", "Full moon face");
reg("🌞", "Sun with face");
reg("⛅", "Sun behind cloud");
reg("🌤️", "Sun behind small cloud");
reg("🌥️", "Sun behind large cloud");
reg("🌦️", "Sun behind rain cloud");
reg("🌧️", "Cloud with rain");
reg("🌩️", "Cloud with lightning");
reg("🌪️", "Tornado");
reg("❄️", "Snowflake");
reg("☃️", "Snowman");
reg("⛄", "Snowman without snow");
reg("☁️", "Cloud");
reg("🌫️", "Fog");

// ── Celebrations ──
reg("🎉", "Party popper");
reg("🎊", "Confetti ball");
reg("🎈", "Balloon");
reg("🎁", "Wrapped gift");
reg("🎀", "Ribbon");
reg("🎆", "Fireworks");
reg("🎇", "Sparkler");
reg("🧨", "Firecracker");
reg("🎃", "Jack-o-lantern");
reg("🎄", "Christmas tree");
reg("🎋", "Tanabata tree");
reg("🎍", "Pine decoration");
reg("🎎", "Japanese dolls");
reg("🎏", "Carp streamer");
reg("🎐", "Wind chime");
reg("🧧", "Red envelope");
reg("🪅", "Piñata");
reg("🪆", "Nesting dolls");
reg("🔮", "Crystal ball");
reg("🪄", "Magic wand");
reg("🧿", "Nazar amulet");
reg("🎑", "Moon viewing ceremony");

// ── Sports & Activities ──
reg("⚽", "Soccer ball");
reg("🏀", "Basketball");
reg("🏈", "American football");
reg("⚾", "Baseball");
reg("🥎", "Softball");
reg("🎾", "Tennis");
reg("🏐", "Volleyball");
reg("🏉", "Rugby football");
reg("🥏", "Flying disc");
reg("🎱", "Pool 8 ball");
reg("🪀", "Yo-yo");
reg("🏓", "Ping pong");
reg("🏸", "Badminton");
reg("🏒", "Ice hockey");
reg("🥍", "Lacrosse");
reg("🏑", "Field hockey");
reg("🥅", "Goal net");
reg("⛳", "Flag in hole");
reg("🪁", "Kite");
reg("🏹", "Bow and arrow");
reg("🎣", "Fishing pole");
reg("🤿", "Diving mask");
reg("🥊", "Boxing glove");
reg("🥋", "Martial arts uniform");
reg("🎿", "Skis");
reg("⛷️", "Skier");
reg("🏂", "Snowboarder");
reg("🪂", "Parachute");
reg("🏋️", "Person lifting weights");
reg("🤸", "Person cartwheeling");
reg("🛹", "Skateboard");
reg("🛼", "Roller skate");
reg("🏄", "Person surfing");
reg("🚣", "Person rowing boat");
reg("🧗", "Person climbing");
reg("🏇", "Horse racing");

// ── Music & Arts ──
reg("🎯", "Bullseye", "direct_hit_3d.png");
reg("🎮", "Video game");
reg("🎲", "Game die");
reg("🧩", "Puzzle piece");
reg("🎵", "Musical note");
reg("🎶", "Musical notes");
reg("🎸", "Guitar");
reg("🎹", "Musical keyboard");
reg("🎺", "Trumpet");
reg("🎻", "Violin");
reg("🥁", "Drum");
reg("🪘", "Long drum");
reg("🎤", "Microphone");
reg("🎧", "Headphone");
reg("🎼", "Musical score");
reg("🎨", "Artist palette");
reg("🎬", "Clapper board");
reg("🎭", "Performing arts");
reg("🎪", "Circus tent");
reg("🎷", "Saxophone");
reg("🪗", "Accordion");
reg("🪕", "Banjo");
reg("🪈", "Flute");

// ── Tech & Objects ──
reg("💻", "Laptop");
reg("📱", "Mobile phone");
reg("⌨️", "Keyboard");
reg("🖥️", "Desktop computer");
reg("🖨️", "Printer");
reg("🖱️", "Computer mouse");
reg("💡", "Light bulb");
reg("🔑", "Key");
reg("🗝️", "Old key");
reg("🔒", "Locked");
reg("🔓", "Unlocked");
reg("📚", "Books");
reg("📖", "Open book");
reg("📕", "Closed book");
reg("📗", "Green book");
reg("📘", "Blue book");
reg("📙", "Orange book");
reg("📓", "Notebook");
reg("📔", "Notebook with decorative cover");
reg("📒", "Ledger");
reg("✏️", "Pencil");
reg("📝", "Memo");
reg("📌", "Pushpin");
reg("📍", "Round pushpin");
reg("📎", "Paperclip");
reg("🖇️", "Linked paperclips");
reg("✂️", "Scissors");
reg("🗂️", "Card index dividers");
reg("📁", "File folder");
reg("📂", "Open file folder");
reg("📊", "Bar chart");
reg("📈", "Chart increasing");
reg("📉", "Chart decreasing");
reg("🗒️", "Spiral notepad");
reg("📋", "Clipboard");
reg("🔍", "Magnifying glass tilted left");
reg("🔎", "Magnifying glass tilted right");
reg("🔬", "Microscope");
reg("🔭", "Telescope");
reg("📡", "Satellite antenna");
reg("💾", "Floppy disk");
reg("💿", "Optical disk");
reg("📀", "DVD");
reg("📷", "Camera");
reg("📸", "Camera with flash");
reg("📹", "Video camera");
reg("🎥", "Movie camera");
reg("📺", "Television");
reg("📻", "Radio");
reg("🧲", "Magnet");
reg("🔧", "Wrench");
reg("🔨", "Hammer");
reg("⚒️", "Hammer and pick");
reg("🛠️", "Hammer and wrench");
reg("⛏️", "Pick");
reg("🪚", "Carpentry saw");
reg("🔩", "Nut and bolt");
reg("⚙️", "Gear");
reg("🧰", "Toolbox");
reg("⛓️", "Chains");
reg("🪝", "Hook");
reg("💊", "Pill");
reg("🩹", "Adhesive bandage");
reg("🩺", "Stethoscope");
reg("🧬", "Dna");
reg("🧪", "Test tube");
reg("🧫", "Petri dish");
reg("🧹", "Broom");
reg("🪣", "Bucket");
reg("🧴", "Lotion bottle");
reg("🛒", "Shopping cart");
reg("🎒", "Backpack");
reg("🪑", "Chair");
reg("🛋️", "Couch and lamp");
reg("🛏️", "Bed");
reg("🪞", "Mirror");
reg("🪟", "Window");
reg("🚪", "Door");
reg("🔔", "Bell");
reg("🔕", "Bell with slash");
reg("📯", "Postal horn");
reg("🗑️", "Wastebasket");
reg("📦", "Package");
reg("🏷️", "Label");
reg("💰", "Money bag");
reg("💴", "Yen banknote");
reg("💵", "Dollar banknote");
reg("💶", "Euro banknote");
reg("💷", "Pound banknote");
reg("💸", "Money with wings");
reg("💳", "Credit card");
reg("🪙", "Coin");
reg("⏰", "Alarm clock");
reg("⌚", "Watch");
reg("⏳", "Hourglass not done");
reg("⌛", "Hourglass done");
reg("🔋", "Battery");
reg("🔌", "Electric plug");
reg("💎", "Gem stone");
reg("💍", "Ring");
reg("👑", "Crown");
reg("🎩", "Top hat");
reg("🧢", "Billed cap");
reg("👓", "Glasses");
reg("🕶️", "Sunglasses");
reg("🥽", "Goggles");

// ── Clothing ──
reg("👗", "Dress");
reg("👘", "Kimono");
reg("👙", "Bikini");
reg("👚", "Woman's clothes");
reg("👛", "Purse");
reg("👜", "Handbag");
reg("👝", "Clutch bag");
reg("🎽", "Running shirt");
reg("🩱", "One-piece swimsuit");
reg("🩲", "Briefs");
reg("🩳", "Shorts");
reg("👔", "Necktie");
reg("👕", "T-shirt");
reg("👖", "Jeans");
reg("🧣", "Scarf");
reg("🧤", "Gloves");
reg("🧥", "Coat");
reg("🧦", "Socks");
reg("👞", "Man's shoe");
reg("👟", "Running shoe");
reg("👠", "High-heeled shoe");
reg("👡", "Woman's sandal");
reg("🩴", "Thong sandal");
reg("👢", "Woman's boot");
reg("👒", "Woman's hat");
reg("🪖", "Military helmet");
reg("⛑️", "Rescue worker's helmet");

// ── Transport & Places ──
reg("🚀", "Rocket");
reg("✈️", "Airplane");
reg("🛸", "Flying saucer");
reg("🚗", "Automobile");
reg("🚕", "Taxi");
reg("🚙", "Sport utility vehicle");
reg("🚌", "Bus");
reg("🚎", "Trolleybus");
reg("🏎️", "Racing car");
reg("🚓", "Police car");
reg("🚑", "Ambulance");
reg("🚒", "Fire engine");
reg("🚐", "Minibus");
reg("🛻", "Pickup truck");
reg("🚚", "Delivery truck");
reg("🚛", "Articulated lorry");
reg("🚜", "Tractor");
reg("🏍️", "Motorcycle");
reg("🛵", "Motor scooter");
reg("🛺", "Auto rickshaw");
reg("🚲", "Bicycle");
reg("🛴", "Kick scooter");
reg("🛹", "Skateboard");
reg("🚂", "Locomotive");
reg("🚆", "Train");
reg("🚇", "Metro");
reg("🚈", "Light rail");
reg("🚝", "Monorail");
reg("🚄", "High-speed train");
reg("🛳️", "Passenger ship");
reg("⛴️", "Ferry");
reg("🛥️", "Motor boat");
reg("🚤", "Speedboat");
reg("⛵", "Sailboat");
reg("🚢", "Ship");
reg("🛶", "Canoe");
reg("🚁", "Helicopter");
reg("🛩️", "Small airplane");
reg("🪂", "Parachute");
reg("🏠", "House");
reg("🏡", "House with garden");
reg("🏢", "Office building");
reg("🏣", "Japanese post office");
reg("🏤", "Post office");
reg("🏥", "Hospital");
reg("🏦", "Bank");
reg("🏨", "Hotel");
reg("🏩", "Love hotel");
reg("🏪", "Convenience store");
reg("🏫", "School");
reg("🏬", "Department store");
reg("🏭", "Factory");
reg("🏯", "Japanese castle");
reg("🏰", "Castle");
reg("💒", "Wedding");
reg("🗼", "Tokyo tower");
reg("🗽", "Statue of Liberty");
reg("⛪", "Church");
reg("🕌", "Mosque");
reg("🛕", "Hindu temple");
reg("🕍", "Synagogue");
reg("⛩️", "Shinto shrine");
reg("🗻", "Mount Fuji");
reg("🏔️", "Snow-capped mountain");
reg("⛺", "Tent");
reg("🏕️", "Camping");
reg("🎡", "Ferris wheel");
reg("🎢", "Roller coaster");
reg("🎠", "Carousel horse");
reg("⛲", "Fountain");
reg("🌍", "Globe showing Europe-Africa");
reg("🌎", "Globe showing Americas");
reg("🌏", "Globe showing Asia-Australia");
reg("🗺️", "World map");

// ── Food & Drink ──
reg("🍕", "Pizza");
reg("🍔", "Hamburger");
reg("🍟", "French fries");
reg("🌭", "Hot dog");
reg("🍿", "Popcorn");
reg("🧂", "Salt");
reg("🥚", "Egg");
reg("🍳", "Cooking");
reg("🥞", "Pancakes");
reg("🧇", "Waffle");
reg("🥓", "Bacon");
reg("🥩", "Cut of meat");
reg("🍗", "Poultry leg");
reg("🍖", "Meat on bone");
reg("🌮", "Taco");
reg("🌯", "Burrito");
reg("🥙", "Stuffed flatbread");
reg("🧆", "Falafel");
reg("🥗", "Green salad");
reg("🥘", "Shallow pan of food");
reg("🍝", "Spaghetti");
reg("🍜", "Steaming bowl");
reg("🍲", "Pot of food");
reg("🍛", "Curry rice");
reg("🍣", "Sushi");
reg("🍱", "Bento box");
reg("🥟", "Dumpling");
reg("🦪", "Oyster");
reg("🍤", "Fried shrimp");
reg("🍙", "Rice ball");
reg("🍚", "Cooked rice");
reg("🍘", "Rice cracker");
reg("🍥", "Fish cake with swirl");
reg("🥠", "Fortune cookie");
reg("🥮", "Moon cake");
reg("🍢", "Oden");
reg("🍡", "Dango");
reg("🍧", "Shaved ice");
reg("🍨", "Ice cream");
reg("🍦", "Soft ice cream");
reg("🥧", "Pie");
reg("🧁", "Cupcake");
reg("🍰", "Shortcake");
reg("🎂", "Birthday cake");
reg("🍮", "Custard");
reg("🍭", "Lollipop");
reg("🍬", "Candy");
reg("🍫", "Chocolate bar");
reg("🍩", "Doughnut");
reg("🍪", "Cookie");
reg("🌰", "Chestnut");
reg("🥜", "Peanuts");
reg("🍯", "Honey pot");
reg("🥛", "Glass of milk");
reg("🍼", "Baby bottle");
reg("☕", "Hot beverage");
reg("🫖", "Teapot");
reg("🍵", "Teacup without handle");
reg("🧃", "Beverage box");
reg("🥤", "Cup with straw");
reg("🧋", "Bubble tea");
reg("🍶", "Sake");
reg("🍺", "Beer mug");
reg("🍻", "Clinking beer mugs");
reg("🥂", "Clinking glasses");
reg("🍷", "Wine glass");
reg("🍸", "Cocktail glass");
reg("🍹", "Tropical drink");
reg("🍾", "Bottle with popping cork");
reg("🧊", "Ice");
reg("🥃", "Tumbler glass");
reg("🫗", "Pouring liquid");

// ── Fruits & Vegetables ──
reg("🍎", "Red apple");
reg("🍏", "Green apple");
reg("🍐", "Pear");
reg("🍊", "Tangerine");
reg("🍋", "Lemon");
reg("🍌", "Banana");
reg("🍉", "Watermelon");
reg("🍇", "Grapes");
reg("🍓", "Strawberry");
reg("🫐", "Blueberries");
reg("🍈", "Melon");
reg("🍒", "Cherries");
reg("🍑", "Peach");
reg("🥭", "Mango");
reg("🍍", "Pineapple");
reg("🥥", "Coconut");
reg("🥝", "Kiwi fruit");
reg("🍅", "Tomato");
reg("🍆", "Eggplant");
reg("🥑", "Avocado");
reg("🫛", "Pea pod");
reg("🥦", "Broccoli");
reg("🥬", "Leafy green");
reg("🥒", "Cucumber");
reg("🌶️", "Hot pepper");
reg("🫑", "Bell pepper");
reg("🌽", "Ear of corn");
reg("🥕", "Carrot");
reg("🧄", "Garlic");
reg("🧅", "Onion");
reg("🥔", "Potato");
reg("🍠", "Roasted sweet potato");
reg("🫚", "Ginger");
reg("🥐", "Croissant");
reg("🥯", "Bagel");
reg("🍞", "Bread");
reg("🥖", "Baguette bread");
reg("🥨", "Pretzel");
reg("🧀", "Cheese wedge");
reg("🥪", "Sandwich");
reg("🫔", "Tamale");

// ── Hands & Gestures ──
reg("👍", "Thumbs up");
reg("👎", "Thumbs down");
reg("👊", "Oncoming fist");
reg("✊", "Raised fist");
reg("🤛", "Left-facing fist");
reg("🤜", "Right-facing fist");
reg("👏", "Clapping hands");
reg("🙌", "Raising hands");
reg("🫶", "Heart hands");
reg("👐", "Open hands");
reg("🤲", "Palms up together");
reg("🤝", "Handshake");
reg("🙏", "Folded hands");
reg("✌️", "Victory hand");
reg("🤞", "Crossed fingers");
reg("🫰", "Hand with index finger and thumb crossed");
reg("🤟", "Love-you gesture");
reg("🤘", "Sign of the horns");
reg("👌", "OK hand");
reg("🤌", "Pinched fingers");
reg("🤏", "Pinching hand");
reg("👈", "Backhand index pointing left");
reg("👉", "Backhand index pointing right");
reg("👆", "Backhand index pointing up");
reg("👇", "Backhand index pointing down");
reg("☝️", "Index pointing up");
reg("✋", "Raised hand");
reg("🤚", "Raised back of hand");
reg("🖐️", "Hand with fingers splayed");
reg("🖖", "Vulcan salute");
reg("🫳", "Palm down hand");
reg("🫴", "Palm up hand");
reg("👋", "Waving hand");
reg("🤙", "Call me hand");
reg("💪", "Flexed biceps");
reg("🦾", "Mechanical arm");
reg("🖕", "Middle finger");
reg("✍️", "Writing hand");
reg("🫵", "Index pointing at the viewer");
reg("🤳", "Selfie");

// ── People ──
reg("👶", "Baby");
reg("👧", "Girl");
reg("🧒", "Child");
reg("👦", "Boy");
reg("👩", "Woman");
reg("🧑", "Person");
reg("👨", "Man");
reg("👵", "Old woman");
reg("🧓", "Older person");
reg("👴", "Old man");
reg("💃", "Woman dancing");
reg("🕺", "Man dancing");
reg("🧑‍🎄", "Mx Claus");
reg("🎅", "Santa Claus");
reg("🤶", "Mrs. Claus");
reg("🧙", "Mage");
reg("🧚", "Fairy");
reg("🧛", "Vampire");
reg("🧜", "Merperson");
reg("🧝", "Elf");
reg("🦸", "Superhero");
reg("🦹", "Supervillain");
reg("🧞", "Genie");
reg("🧟", "Zombie");
reg("🤷", "Person shrugging");
reg("🤦", "Person facepalming");
reg("🙋", "Person raising hand");
reg("🙇", "Person bowing");
reg("🧑‍💻", "Technologist");
reg("🧑‍🎨", "Artist");
reg("🧑‍🚀", "Astronaut");
reg("🧑‍🔬", "Scientist");
reg("🧑‍🍳", "Cook");
reg("🧑‍🎓", "Student");
reg("🧑‍🏫", "Teacher");
reg("🧑‍⚕️", "Health worker");
reg("🧑‍🌾", "Farmer");
reg("🧑‍🔧", "Mechanic");
reg("🧑‍💼", "Office worker");
reg("🧑‍🚒", "Firefighter");

// ── Awards ──
reg("🏆", "Trophy");
reg("🥇", "1st place medal");
reg("🥈", "2nd place medal");
reg("🥉", "3rd place medal");
reg("🏅", "Sports medal");
reg("🎖️", "Military medal");

// ── Flags ──
reg("🏁", "Chequered flag");
reg("🚩", "Triangular flag");
reg("🎌", "Crossed flags");
reg("🏴", "Black flag");
reg("🏳️", "White flag");
reg("🏳️‍🌈", "Rainbow flag");
reg("🏳️‍⚧️", "Transgender flag");
reg("🏴‍☠️", "Pirate flag");
reg("🇧🇷", "Flag Brazil", "flag_brazil_3d.png");
reg("🇺🇸", "Flag United States", "flag_united_states_3d.png");
reg("🇯🇵", "Flag Japan", "flag_japan_3d.png");
reg("🇰🇷", "Flag South Korea", "flag_south_korea_3d.png");
reg("🇬🇧", "Flag United Kingdom", "flag_united_kingdom_3d.png");
reg("🇫🇷", "Flag France", "flag_france_3d.png");
reg("🇩🇪", "Flag Germany", "flag_germany_3d.png");
reg("🇮🇹", "Flag Italy", "flag_italy_3d.png");
reg("🇪🇸", "Flag Spain", "flag_spain_3d.png");
reg("🇵🇹", "Flag Portugal", "flag_portugal_3d.png");
reg("🇦🇷", "Flag Argentina", "flag_argentina_3d.png");
reg("🇲🇽", "Flag Mexico", "flag_mexico_3d.png");

// ── Symbols ──
reg("♻️", "Recycling symbol");
reg("⚠️", "Warning");
reg("🚫", "Prohibited");
reg("❌", "Cross mark");
reg("⭕", "Hollow red circle");
reg("✅", "Check mark button");
reg("☑️", "Check box with check");
reg("❓", "Red question mark");
reg("❗", "Red exclamation mark");
reg("‼️", "Double exclamation mark");
reg("⁉️", "Exclamation question mark");
reg("💤", "Zzz");
reg("💬", "Speech balloon");
reg("💭", "Thought balloon");
reg("🗯️", "Right anger bubble");
reg("♾️", "Infinity");
reg("🔊", "Speaker high volume");
reg("🔇", "Muted speaker");
reg("📢", "Loudspeaker");
reg("📣", "Megaphone");
reg("🏧", "ATM sign");
reg("♿", "Wheelchair symbol");
reg("🅿️", "P button");
reg("🈶", "Japanese 'not free of charge' button");
reg("🈚", "Japanese 'free of charge' button");

// ── Misc Objects ──
reg("🪩", "Mirror ball");
reg("🎗️", "Reminder ribbon");
reg("🎟️", "Admission tickets");
reg("🎫", "Ticket");
reg("🧸", "Teddy bear");
reg("🪆", "Nesting dolls");
reg("🖼️", "Framed picture");
reg("🛍️", "Shopping bags");
reg("🎀", "Ribbon");
reg("📿", "Prayer beads");
reg("🔗", "Link");
reg("🧲", "Magnet");
reg("🪪", "Identification card");
reg("📮", "Postbox");
reg("✉️", "Envelope");
reg("📧", "E-mail");
reg("📩", "Envelope with arrow");
reg("📨", "Incoming envelope");
reg("🗓️", "Spiral calendar");
reg("📅", "Calendar");
reg("📆", "Tear-off calendar");

// ── Zodiac (bonus) ──
reg("♈", "Aries");
reg("♉", "Taurus");
reg("♊", "Gemini");
reg("♋", "Cancer");
reg("♌", "Leo");
reg("♍", "Virgo");
reg("♎", "Libra");
reg("♏", "Scorpio");
reg("♐", "Sagittarius");
reg("♑", "Capricorn");
reg("♒", "Aquarius");
reg("♓", "Pisces");

interface FluentEmojiProps {
  emoji: string;
  size?: number;
  className?: string;
}

function FluentEmojiInner({ emoji, size = 20, className = "" }: FluentEmojiProps) {
  const mapping = EMOJI_MAP[emoji];

  if (!mapping) {
    return <span className={className} style={{ fontSize: size, lineHeight: 1 }}>{emoji}</span>;
  }

  const url = `${CDN_BASE}/${encodeURIComponent(mapping.folder)}/Default/3D/${encodeURIComponent(mapping.file)}`;

  return (
    <img
      src={url}
      alt={emoji}
      width={size}
      height={size}
      className={`inline-block shrink-0 ${className}`}
      style={{ width: size, height: size }}
      loading="eager"
      onError={(e) => {
        const span = document.createElement("span");
        span.textContent = emoji;
        span.style.fontSize = `${size}px`;
        span.style.lineHeight = "1";
        span.className = className;
        e.currentTarget.replaceWith(span);
      }}
    />
  );
}

export const FluentEmoji = memo(FluentEmojiInner);
